# Configure main menu and social menu
social:
  - identifier: github
    name: GitHub
    url: https://github.com/sahaba-ai/awesome-arabic-speakers
    params:
      icon: brand-github
  - identifier: telegram
    name: Telegram
    url: https://t.me/AwesomeArabicSpeakers
    params:
      icon: brand-telegram
  - identifier: twitter
    name: Twitter
    url: https://x.com/AwesomeArabic
    params:
      icon: brand-twitter
